[package]
name = "picaro-rs"
version = "0.1.0"
edition = "2024"

[features]
_masking = ["rand_chacha"]
masking_level_1 = ["_masking"]
masking_level_2 = ["_masking"]
masking_level_3 = ["_masking"]

[dependencies]
rand_chacha = { version = "0.9.0", default-features = false, features = [
  "os_rng",
], optional = true }

[dev-dependencies]
criterion = { version = "0.7" }

[[bench]]
name = "encrypt"
harness = false

[[bench]]
name = "decrypt"
harness = false
