[package]
name = "picaro-rs"
version = "0.1.0"
edition = "2024"
description = "An attempt at an implementation of the Picaro cipher, for a university project."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlephCubed/picaro-rs"
authors = ["Josiah Nelson"]

[dependencies]
rand_chacha = { version = "0.9.0", default-features = false, features = [
  "os_rng",
] }

[dev-dependencies]
criterion = { version = "0.7" }
aes = "0.8.4"

[[bench]]
name = "picaro_encrypt"
path = "benches/picaro/encrypt.rs"
harness = false

[[bench]]
name = "picaro_decrypt"
path = "benches/picaro/decrypt.rs"
harness = false

[[bench]]
name = "picaro_s_box"
path = "benches/picaro/s_box.rs"
harness = false

[[bench]]
name = "picaro_expansion"
path = "benches/picaro/expansion.rs"
harness = false

[[bench]]
name = "picaro_compression"
path = "benches/picaro/compression.rs"
harness = false

[[bench]]
name = "aes_s_box"
path = "benches/aes/s_box.rs"
harness = false

[[bench]]
name = "aes_encrypt_extern"
path = "benches/aes/encrypt_extern.rs"
harness = false

[[bench]]
name = "aes_decrypt_extern"
path = "benches/aes/decrypt_extern.rs"
harness = false
