[package]
name = "picaro-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_chacha = { version = "0.9.0", default-features = false, features = [
  "os_rng",
] }

[dev-dependencies]
criterion = { version = "0.7" }

[[bench]]
name = "picaro_encrypt"
path = "benches/picaro/encrypt.rs"
harness = false

[[bench]]
name = "picaro_decrypt"
path = "benches/picaro/decrypt.rs"
harness = false

[[bench]]
name = "picaro_s_box"
path = "benches/picaro/s_box.rs"
harness = false

[[bench]]
name = "picaro_expansion"
path = "benches/picaro/expansion.rs"
harness = false

[[bench]]
name = "picaro_compression"
path = "benches/picaro/compression.rs"
harness = false

[[bench]]
name = "aes_s_box"
path = "benches/aes/s_box.rs"
harness = false
